import AppBar from "@/components/AppBar";
import "./globals.scss";
import Providers from "@/components/Providers";
import "bootstrap/dist/css/bootstrap.min.css";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Next-Auth Tutorial",
  description: "Generated by Sakura Dev",
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout(props: Props) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* <AppBar /> */}
          {props.children}
        </Providers>
      </body>
    </html>
  );
}
